services:
  web:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joke_db
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysqldata: {}
